### PR TITLE
CCS811 improvements

### PR DESCRIPTION
**Pull request by AkosLukacs**
Hi, some improvements to the CCS811 module. Almost ready, but if you have some time, maybe take a look.
Done so far:
- support alternative I2C address
- support different sample rates
- use nWake to save power on lower sample rates
- moved the jsDoc from the constructor to the `.connect()` function, so the description will be visible on the website's reference section.
- and some docs
- of course my auto-format doesn't agree your auto-format. Do you have an editorconfig or something maybe?

Wip: Environmental data (temperature and humidity) compensation.

Btw, do you use this sensor?

### CODE REVIEW

**Comment by gfwilliams** [comment]
Looks good, thanks! - let me know when you're ready to merge.

I don't have any specific auto format style, no. It's basically K&R style with 2 spaces indent and curly braces on the same line, although what goes on inside the line itself isn't really prescribed. This might be interesting: http://www.espruino.com/FAQ#is-there-a-coding-style-i-should-use-

And yes, the sensor's in the Nordic Thingy:52 so this module gets included in the Espruino firmware for that - but it does mean that the module needs to stay backwards compatible :)

**Comment by AkosLukacs** [comment]
Oh, there are tons of "small" things in Espruino you wouldn't even think about. Like what lines should be copy-pasted <3
It's still the same basic API, just "better" :)

**Comment by AkosLukacs** [comment]
Added `setEnvData(humidity, temperature)` to use temperature and humidity compensation
Added `setMode(mode)` to change the sampling rate
Added firmware updater, so now there is a "native" Espruino solution to update the firmware in the CCS811. My main concern was that the 5k binaries wouldn't fit, but looks like it just works fine!

Messed with constants, but looks like closure compile doesn't want to inline them. (no-inlining in the original CCS811 code either)

Looks like there was a "something" in the [original code](https://github.com/espruino/EspruinoDocs/blob/master/devices/CCS811.js#L47): you read from register 0x80, but there is no 0x80 register in the datasheet. Or maybe there was, but didn't find it in either `[v1-00] 2016-Dec-23` or `[v1-06] 2019-Feb-07` (couldn't find other versions)

Ok, there is a slight breaking change (don't touch working code...): With fw 2.xx you can read the `isNew` information in one I2C read, but that doesn't work with fw 1.1.
Mainly that's why I created the firmware updater module. It's not small - 20k unminified, 1100-1200 vars usage in Pixl.JS. But that should still fit in all official boards, and even the ESP8266. The updater contains the v.2.0.0 and v.2.0.1 versions, and lots of info messages, so everybody should be able to upgrade in a couple of minutes.

**Comment by AkosLukacs** [comment]
It's ready.
Tried to get closure compiler to inline the constants, but no luck. The module grew a bit, so manually shortened the constant property names, that saved 22 vars (roughly 10%).

**Comment by gfwilliams** [comment]
That's great - thanks!

Sorry I missed your last comments for some reason. 

Yeah, splitting the object up into constants/regs as you've done is definitely better and usually means closure will inline at least some of it.

I need to look into why it's not touching constants though as it used to - I should maybe move to including a local closure compiler in the docs repo. It'd ensure everything stayed working at least and I guess might provide some info on why things weren't getting folded down

**Comment by AkosLukacs** [comment]
No worries, at least had time for some more tweaks :)
Have you seen https://github.com/espruino/EspruinoDocs/pull/506?

**Comment by gfwilliams** [comment]
I did, thanks! I'm a bit unsure at the moment but I'll post more info on there

**Pull request merged**
