### PR TITLE
Update Puck.js.md

### PR DESCRIPTION
**Pull request by kurtgrung**
[Getting Started Guide] - link broken

### CODE REVIEW

**Comment by gfwilliams** [comment]
Hi - I just wanted to check - how exactly is this link broken?

On https://www.espruino.com/Puck.js#tutorials (which is what this page is used to produce) the 'Getting Started Guide' link appears to work fine and take me to https://www.espruino.com/Quick+Start+BLE#puckjs ?

**Comment by kurtgrung** [comment]
gives a GitHub 404 when i click the link.

**Comment by gfwilliams** [comment]
Where? On https://github.com/espruino/EspruinoDocs/blob/master/boards/Puck.js.md ?

Because we do have right at the top of that page:

> Please view the correctly rendered version of this page at https://www.espruino.com/Puck.js. Links, lists, videos, search, and other features will not work correctly when viewed on GitHub

I have the repo on GitHub in markdown so that it's easy to edit and contribute too, but not everything works when viewed from GitHub

**Comment by kurtgrung** [comment]
yes on > https://github.com/espruino/EspruinoDocs/blob/master/boards/Puck.js.md

**Comment by gfwilliams** [comment]
Ok, thanks - but I'm afraid I don't think this in particular is worth fixing.

I guess maybe at some point someone could come up with a script to change *every* relative link in the repository, so at least those work - but for instance things like `APPEND_USES: ` that you see in GitHub will never work. It's why we have the comment with the big warning sign at the top of every page.

**Pull request closed without merging**
