### PR TITLE
Slimmed BME280 module; MQTT module bug fix

### PR DESCRIPTION
**Pull request by rmcubed**
Removed cruft.
Standardised constants.
Made compatible with Closure Advanced Optimisation level
Contributed fully optimised min.js

### CODE REVIEW

**Comment by rmcubed** [comment]
Now added improvements to MQTT module

**Comment by gfwilliams** [comment]
Looks awesome - thanks! As I said in the forum, I'll add something that detects `@compilation_level ADVANCED_OPTIMIZATIONS` in the source file, so we don't have to store a minified copy in here

**Comment by gfwilliams** [comment]
Hmm, when I run through with advanced optimisations I get:

```
function d(a,b){this.b=a;b=b||{};this.debug=b.debug;this.f(242,1);this.f(244,39);this.f(245,160);this.J()}d.prototype.g=function(a,b){var c=new Uint8Array(a.length+b.length);c.set(a);c.set(b,a.length);return c};d.prototype.a=function(a,b){var c=(a<<8)+b;c&32768&&(c=-(c-1^65535));return c};d.prototype.f=function(a,b){this.b.writeTo(118,[a,b])};d.prototype.J=function(){this.b.writeTo(118,136);var a=this.b.readFrom(118,24);this.b.writeTo(118,161);a=this.g(a,this.b.readFrom(118,1));this.b.writeTo(118,
225);a=this.g(a,this.b.readFrom(118,7));this.c=a[1]<<8|a[0];this.H=this.a(a[3],a[2]);this.I=this.a(a[5],a[4]);this.u=a[7]<<8|a[6];this.v=this.a(a[9],a[8]);this.w=this.a(a[11],a[10]);this.A=this.a(a[13],a[12]);this.B=this.a(a[15],a[14]);this.C=this.a(a[17],a[16]);this.D=this.a(a[19],a[18]);this.F=this.a(a[21],a[20]);this.G=this.a(a[23],a[22]);this.i=a[24];this.j=this.a(a[26],a[25]);this.l=a[27];this.m=a[28]<<4|15&a[29];this.o=a[30]<<4|a[29]>>4&15;this.s=a[31]};d.prototype.readRawData=function(){this.b.writeTo(118,
247);var a=this.b.readFrom(118,8);this.pres_raw=a[0]<<12|a[1]<<4|a[2]>>4;this.temp_raw=a[3]<<12|a[4]<<4|a[5]>>4;this.hum_raw=a[6]<<8|a[7]};d.prototype.calibration_T=function(a){var b;b=(a/16384-this.c/1024)*this.H;a=(a/131072-this.c/8192)*(a/131072-this.c/8192)*this.I;this.h=b+a;return(b+a)/5120*100};d.prototype.calibration_P=function(a){var b,c;b=this.h/2-64E3;c=b*b*this.C/32768;c+=b*this.B*2;c=c/4+65536*this.A;b=(this.w*b*b/524288+this.v*b)/524288;b=(1+b/32768)*this.u;if(0===b)return 0;a=6250*(1048576-
a-c/4096)/b;b=this.G*a*a/2147483648;c=a*this.F/32768;return a+=(b+c+this.D)/16};d.prototype.calibration_H=function(a){var b;b=this.h-76800;b=((a<<14)-(this.m<<20)-this.o*b+16384>>15)*((((b*this.s>>10)*((b*this.l>>11)+32768)>>10)+2097152)*this.j+8192>>14);b-=((b>>15)*(b>>15)>>7)*this.i>>4;b=0>b?0:b;return(419430400<b?419430400:b)>>12};exports.connect=function(a,b){return new d(a,b)}
```

vs your:

```
function d(c,b){this.a=c;b=b||{};this.debug=b.debug;this.a.writeTo(118,[242,1]);this.a.writeTo(118,[244,39]);this.a.writeTo(118,[245,160]);this.a.writeTo(118,136);var a=this.a.readFrom(118,24);this.a.writeTo(118,161);a=e(a,this.a.readFrom(118,1));this.a.writeTo(118,225);a=e(a,this.a.readFrom(118,7));this.b=a[1]<<8|a[0];this.D=f(a[3],a[2]);this.F=f(a[5],a[4]);this.m=a[7]<<8|a[6];this.o=f(a[9],a[8]);this.s=f(a[11],a[10]);this.u=f(a[13],a[12]);this.v=f(a[15],a[14]);this.w=f(a[17],a[16]);this.A=f(a[19],
a[18]);this.B=f(a[21],a[20]);this.C=f(a[23],a[22]);this.f=a[24];this.g=f(a[26],a[25]);this.h=a[27];this.i=a[28]<<4|15&a[29];this.j=a[30]<<4|a[29]>>4&15;this.l=a[31]}function e(c,b){var a=new Uint8Array(c.length+b.length);a.set(c);a.set(b,c.length);return a}function f(c,b){var a=(c<<8)+b;a&32768&&(a=-(a-1^65535));return a}
d.prototype.readRawData=function(){this.a.writeTo(118,247);var c=this.a.readFrom(118,8);this.pres_raw=c[0]<<12|c[1]<<4|c[2]>>4;this.temp_raw=c[3]<<12|c[4]<<4|c[5]>>4;this.hum_raw=c[6]<<8|c[7]};d.prototype.calibration_T=function(c){var b;b=(c/16384-this.b/1024)*this.D;c=(c/131072-this.b/8192)*(c/131072-this.b/8192)*this.F;this.c=b+c;return(b+c)/5120*100};
d.prototype.calibration_P=function(c){var b,a;b=this.c/2-64E3;a=b*b*this.w/32768;a+=b*this.v*2;a=a/4+65536*this.u;b=(this.s*b*b/524288+this.o*b)/524288;b=(1+b/32768)*this.m;if(0===b)return 0;c=6250*(1048576-c-a/4096)/b;b=this.C*c*c/2147483648;a=c*this.B/32768;return c+=(b+a+this.A)/16};
d.prototype.calibration_H=function(c){var b;b=this.c-76800;b=((c<<14)-(this.i<<20)-this.j*b+16384>>15)*((((b*this.l>>10)*((b*this.h>>11)+32768)>>10)+2097152)*this.g+8192>>14);b-=((b>>15)*(b>>15)>>7)*this.f>>4;b=0>b?0:b;return(419430400<b?419430400:b)>>12};exports.connect=function(c,b){return new d(c,b)};
```

Yours is *far closer* to what I get from SIMPLE_OPTIMISATION?

I don't believe I have a BME280, so please can you test it still works?

The minification that's done by `minify.js` wraps the whole function in `(function(){  ... })();`, and then unwraps it at the end. It basically adds scoping, so that any locally defined symbols can get easily renamed/removed.

**Comment by rmcubed** [comment]
Probably won't be next weekend until I can test. Does look like simple optimization you are right. It took me a while to notice that in the web UI for Closure, when you switch javascript you need to switch the advanced option back on.

**Pull request merged**
