### PR TITLE
SH1106 OLED driver

### PR DESCRIPTION
**Pull request by jhrichards**

### CODE REVIEW

**Comment by gfwilliams** [comment]
Sorry for the late response - I'm on holiday at the moment but will be back next week. Any reason for closing this pr?

**Comment by gfwilliams** [comment]
It looks good - it's always good to have more display drivers

**Comment by jhrichards** [comment]
I think I need to learn how to drive git properly.
I've also got a DOGXL160 that I've never done anything with, maybe...

**Comment by gfwilliams** [comment]
Thanks!

**Pull request merged**
