### PR TITLE
update EspruinoESP8266.md

### PR DESCRIPTION
**Pull request by MaBecker**

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks for the updates - but please can you leave the paths flat (ie. not `/tutorials`) as that'll break the HTML files that are produced by the build script

**Comment by MaBecker** [comment]
if `/tutorials` is missing the link is broken - like now

**Comment by gfwilliams** [comment]
Only in the `.md` file on GitHub - and many things are broken in that.

On http://www.espruino.com/EspruinoESP8266 it works fine

Also - if you viewed this as a file on a PC, `/tutorials` would also be broken I guess as it'll try looking in the root drive of the computer.

Ideally the script would be changed to remove the complete path from the link, and all the other links in EspruinoDocs would be changed - but I think it'd unlikely anyone is going to do that :)

**Comment by MaBecker** [comment]
Thanks, now i understand

**Comment by gfwilliams** [comment]
Thanks! However it still has the `.md` - same reasons I'm afraid.

Does GitHub have a way of doing banners? I think it'd help if I could have this repo mention that the 'compiled' docs are on the main Espruino site - it's a big help having APPEND_JSDOCS/etc working properly

**Comment by MaBecker** [comment]
Ups, sorry ...

**Comment by gfwilliams** [comment]
Thanks! :)

**Pull request merged**
