### PR TITLE
Revert "Fixing ws issue that didn't appear till it was delivered"

### PR DESCRIPTION
**Pull request by nkolban**
Reverts espruino/EspruinoDocs#177

### CODE REVIEW

**Comment by samehhady** [comment]
Hi Gordon,

I've submitted new PR and when it was merged I couldn't see my module working.
So i thought it was related to my module and submitted new fix adding function like how it was.
Then i found it again not working, at this moment i realized that I am still actually referring to the old  ws module and my changes didn't reflect yet in the IDE.

So I've asked @nkolban to revert back to the previous version as it was working properly for me.

Can you please copy my latest ws.js updates to Espruino.com/modules so it would reflect in the IDE

**Comment by gfwilliams** [comment]
Hi - yes, the process for going from EspuinoDocs to the website is manual though - so I can't afford to keep doing updates for you every day :)

**Comment by samehhady** [comment]
I understand now, Sorry I thought it is done automatically once you merge.

With my last push I did lots of updates to the module and the websocket page, I've also added several examples including how to run a node.js server and broadcast messages.

I think the updates got valuable info that would help others testing it.

I will not do any further updates till a bug appear or something but these updates really needs to be published :)

**Comment by gfwilliams** [comment]
Ok, just done.

**Pull request merged**
