### PR TITLE
add new modue hmac256

### PR DESCRIPTION
**Pull request by MaBecker**
based on hmac

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks! But wasn't it possible just to add this single function to HMAC?

```
exports.SHA256 = function(key) {
  return new exports.HMAC(key, require('crypto').SHA256, 64, 32);
};
```

Or was there something else?

**Comment by MaBecker** [comment]
Wow, ok looks like have been way much over motivated..... Sure why not just, one file. What happens if `require('crypto').SHA256` failes because sha256 is not available?

**Comment by gfwilliams** [comment]
Sorry! Well, it'll only fail when the function is executed - there's no problem with it being in there and SHA256 not being supported if it's not used.

**Comment by MaBecker** [comment]
please check again.

**Comment by gfwilliams** [comment]
Looks great - thanks for doing that!

**Pull request merged**
