### PR TITLE
fix Badge.getName

### PR DESCRIPTION
**Pull request by MaBecker**

### CODE REVIEW

**Comment by gfwilliams** [comment]
Does it not work? Did you test the replacement?

I'd be pretty sure your change to:

```
Badge.getName = () => {
  NRF.getAddress()
    .substr(-5)
    .replace(":", "");
};
```

actually breaks it since you're no longer returning any value from the function.

**Comment by MaBecker** [comment]
Ups, have to check again

**Comment by gfwilliams** [comment]
Just checked and the original:

```
E.getName = () => NRF.getAddress().substr(-5).replace(":", "");
```

works fine to report the last 4 digits, but should probably actually be:

```
E.getName = () => "Pixl.js "+NRF.getAddress().substr(-5).replace(":", "");
```

**Comment by MaBecker** [comment]
```
Badge = global.Badge || {};

Badge.getName = () =>
  NRF.getAddress()
    .substr(-5)
    .replace(":", "");
```
output

```
|  __|___ ___ ___ _ _|_|___ ___
|  __|_ -| . |  _| | | |   | . |
|____|___|  _|_| |___|_|_|_|___|
         |_| espruino.com
 2v04.199 (c) 2019 G.Williams
>Uncaught SyntaxError: Unexpected end of Input
 at line 1 col 23
Badge.getName = () =>
                      ^
```

Ok,  put all in one line and it works ;-)
```
Badge = global.Badge || {};
Badge.getName = () => NRF.getAddress().substr(-5).replace(":", "");
console.log(Badge.getName());
// output
>c3ec
```

**Comment by MaBecker** [comment]
Ready to go, if you like ;-)

**Pull request closed without merging**
