### PR TITLE
Add WebServer module

### PR DESCRIPTION
**Pull request by EthraZa**
Don't have Apache or Nginx to Espruino? Your problems are over! 
Adding Espruino WebServer v1.0 module.

### CODE REVIEW

**Comment by gfwilliams** [comment]
Looks great, thanks! Are you sure about `String.prototype.byteLength` though? since there's no unicode in Espruino the bytelength always equals the normal length.

**Comment by wilberforce** [comment]
@EthraZa

The use of trying literals might simplify of the code... 


```
for (var i=0;i<5;i++) 
  console.log(`No.${i} Hello World, even ${i*0.25}`);

```

**Comment by wilberforce** [comment]
Trying literals - should be string literals !

**Comment by gfwilliams** [comment]
String literals also allow you to have newlines in them, so including webpages is really easy now :)

**Comment by EthraZa** [comment]
Hi, yeah, the byLenght was just a long shoot to try to have a Content-Lenght. Since I know its probably wrong sometimes, maybe it's just better to cut it off to save space.
About String literals, yeah, I know, but they still look so strange to me that I get my self avoiding them... I need a mental work here to force my hand to use it :)

I'll improve that stuff for the next version where I'll try to combine it with @wilberforce [FlashStore](http://forum.espruino.com/conversations/283045/)

Thx

**Comment by wilberforce** [comment]
@EthraZa
After seeing your interest in the forums, I had another look FlashStore. Since it was first made, something has changed with the way prototype works and the way I was adding new methods on the fly doesn't work any more....


If you are playing to use this stuff on the esp8266, You should see how many js vars you have left as I have feeling you will be running out of space

**Pull request merged**
