### PR TITLE
Add DANE Arwes module

### PR DESCRIPTION
**Pull request by OmegaRogue**
Added a module for UI based on https://arwes.dev for use in my BangleJs Apps

### CODE REVIEW

**Comment by gfwilliams** [comment]
Hi - this looks good - however, is the intention to add more to this in the future?

It seems overkill to add a module to Espruino that basically just draws 9 rectangles - I'm not sure it's going to get a bunch of use outside of your specific apps. Maybe I could find a way to define modules in BangleApps that can be used there?

**Comment by OmegaRogue** [comment]
> Hi - this looks good - however, is the intention to add more to this in the future?
> 
> It seems overkill to add a module to Espruino that basically just draws 9 rectangles - I'm not sure it's going to get a bunch of use outside of your specific apps. Maybe I could find a way to define modules in BangleApps that can be used there?

I'm currently working on adding versions of functions like E.showAlert, E.showMenu, E.showMessage and E.showPrompt to it,
but I'm not expecting anyone else to really use it, so being able to define modules in BangleApps would probably be the better option

**Comment by OmegaRogue** [comment]
I've tried to compile all the functions in the module, but the IDE said `WARNING: Function marked with "compiled" uploaded in source form` and then couldn't find the functions when they were used.

**Comment by gfwilliams** [comment]
> I've tried to compile all the functions in the module

Was that in the emulator or a Bangle? 

Honestly trying to compile the functions wouldn't have been a great idea anyway though. There are a few of things (I mentioned some in your original post) that should speed the code up.

**Comment by OmegaRogue** [comment]
> > I've tried to compile all the functions in the module
> 
> Was that in the emulator or a Bangle?
> 
> Honestly trying to compile the functions wouldn't have been a great idea anyway though. There are a few of things (I mentioned some in your original post) that should speed the code up.

it was on both a bangle and on the emulator

**Comment by gfwilliams** [comment]
Thanks - I'll see about tweaking the app loader to let it pull in modules now.

**Pull request closed without merging**
