### PR TITLE
MQTT module

### PR DESCRIPTION
**Pull request by ltj**
Hey Gordon,

Based on and inspired by your socket/MQTT example I have created a MQTT client module that implements a protocol subset and some crude approximations. It's a work in progress and lacks a lot but it adds publish, subscribe, unsubscribe, connect and disconnect and wraps it up in a nice module with a publish event for ease of use. I'll continue to work on it and also look into a more complete implementation (maybe a port of the Eclipse PAHO JS client).

Cheers,
Lars

### CODE REVIEW

**Comment by gfwilliams** [comment]
Wow, this look amazing. Thanks! This'll be really handy.

Just 2 questions:

* Why do you need the Object.create in `Object.create(new MQTT(server, options));`? It's probably not an issue but I just haven't seen it done like that before.
* Would it be possible to do something like this:

```
MQTT.prototype.connect = function(client) {
  var mqo = this;
  var onConnect = function() { 
    ... 
  };
  if (client) onConnect(client);
  else client = require("net").connect({host : mqo.server, port: mqo.port}, onConnect);
}
```

I only ask because it would be really nice not to have to use MQTT over the network - for example you could point it at a bluetooth serial device on Serial1, or maybe even some other kind of low power radio as long as `x.write()` and `x.on('data', ..)` were implemented.

**Comment by gfwilliams** [comment]
Wow, this look amazing. Thanks! This'll be really handy.

Just 2 questions:

* Why do you need the Object.create in `Object.create(new MQTT(server, options));`? It's probably not an issue but I just haven't seen it done like that before.
* Would it be possible to do something like this:

```
MQTT.prototype.connect = function(client) {
  var mqo = this;
  var onConnect = function() { 
    ... 
  };
  if (client) onConnect(client);
  else client = require("net").connect({host : mqo.server, port: mqo.port}, onConnect);
}
```

I only ask because it would be really nice not to have to use MQTT over the network - for example you could point it at a bluetooth serial device on Serial1, or maybe even some other kind of low power radio as long as `x.write()` and `x.on('data', ..)` were implemented.

**Comment by gfwilliams** [comment]
Wow, this look amazing. Thanks! This'll be really handy.

Just 2 questions:

* Why do you need the Object.create in `Object.create(new MQTT(server, options));`? It's probably not an issue but I just haven't seen it done like that before.
* Would it be possible to do something like this:

```
MQTT.prototype.connect = function(client) {
  var mqo = this;
  var onConnect = function() { 
    ... 
  };
  if (client) onConnect(client);
  else client = require("net").connect({host : mqo.server, port: mqo.port}, onConnect);
}
```

I only ask because it would be really nice not to have to use MQTT over the network - for example you could point it at a bluetooth serial device on Serial1, or maybe even some other kind of low power radio as long as `x.write()` and `x.on('data', ..)` were implemented.

**Comment by gfwilliams** [comment]
Wow, this look amazing. Thanks! This'll be really handy.

Just 2 questions:

* Why do you need the Object.create in `Object.create(new MQTT(server, options));`? It's probably not an issue but I just haven't seen it done like that before.
* Would it be possible to do something like this:

```
MQTT.prototype.connect = function(client) {
  var mqo = this;
  var onConnect = function() { 
    ... 
  };
  if (client) onConnect(client);
  else client = require("net").connect({host : mqo.server, port: mqo.port}, onConnect);
}
```

I only ask because it would be really nice not to have to use MQTT over the network - for example you could point it at a bluetooth serial device on Serial1, or maybe even some other kind of low power radio as long as `x.write()` and `x.on('data', ..)` were implemented.

**Comment by gfwilliams** [comment]
Wow, this look amazing. Thanks! This'll be really handy.

Just 2 questions:

* Why do you need the Object.create in `Object.create(new MQTT(server, options));`? It's probably not an issue but I just haven't seen it done like that before.
* Would it be possible to do something like this:

```
MQTT.prototype.connect = function(client) {
  var mqo = this;
  var onConnect = function() { 
    ... 
  };
  if (client) onConnect(client);
  else client = require("net").connect({host : mqo.server, port: mqo.port}, onConnect);
}
```

I only ask because it would be really nice not to have to use MQTT over the network - for example you could point it at a bluetooth serial device on Serial1, or maybe even some other kind of low power radio as long as `x.write()` and `x.on('data', ..)` were implemented.

**Comment by gfwilliams** [comment]
Wow, this look amazing. Thanks! This'll be really handy.

Just 2 questions:

* Why do you need the Object.create in `Object.create(new MQTT(server, options));`? It's probably not an issue but I just haven't seen it done like that before.
* Would it be possible to do something like this:

```
MQTT.prototype.connect = function(client) {
  var mqo = this;
  var onConnect = function() { 
    ... 
  };
  if (client) onConnect(client);
  else client = require("net").connect({host : mqo.server, port: mqo.port}, onConnect);
}
```

I only ask because it would be really nice not to have to use MQTT over the network - for example you could point it at a bluetooth serial device on Serial1, or maybe even some other kind of low power radio as long as `x.write()` and `x.on('data', ..)` were implemented.

**Comment by gfwilliams** [comment]
Wow, this look amazing. Thanks! This'll be really handy.

Just 2 questions:

* Why do you need the Object.create in `Object.create(new MQTT(server, options));`? It's probably not an issue but I just haven't seen it done like that before.
* Would it be possible to do something like this:

```
MQTT.prototype.connect = function(client) {
  var mqo = this;
  var onConnect = function() { 
    ... 
  };
  if (client) onConnect(client);
  else client = require("net").connect({host : mqo.server, port: mqo.port}, onConnect);
}
```

I only ask because it would be really nice not to have to use MQTT over the network - for example you could point it at a bluetooth serial device on Serial1, or maybe even some other kind of low power radio as long as `x.write()` and `x.on('data', ..)` were implemented.

**Comment by gfwilliams** [comment]
Sorry - got some internet connection problems at the moment, so I'm not sure if the posts are going through!

**Comment by ltj** [comment]
Thanks, Gordon.

I'm no JS ninja so I thought the Object.create(new MQTT(server, options)); was
the way to go if I wanted to create a new Object based on the MQTT
prototype. Only reason being that I wanted the event system (on/emit) built
in - is there a more appropriate way of doing that?

Definitely yes to your second point. That would just make it more useful.

Feel free to alter the code as you see fit. Otherwise I'll have a go at it
any time soon.

On Thu, Jan 22, 2015 at 10:16 AM, Gordon Williams <notifications@github.com>
wrote:

> Wow, this look amazing. Thanks! This'll be really handy.
>
> Just 2 questions:
>
>    - Why do you need the Object.create in Object.create(new MQTT(server,
>    options));? It's probably not an issue but I just haven't seen it done
>    like that before.
>    - Would it be possible to do something like this:
>
> MQTT.prototype.connect = function(client) {
>   var mqo = this;
>   var onConnect = function() {
>     ...
>   };
>   if (client) onConnect(client);
>   else client = require("net").connect({host : mqo.server, port: mqo.port}, onConnect);
> }
>
> I only ask because it would be really nice not to have to use MQTT over
> the network - for example you could point it at a bluetooth serial device
> on Serial1, or maybe even some other kind of low power radio as long as
> x.write() and x.on('data', ..) were implemented.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/espruino/EspruinoDocs/pull/110#issuecomment-70991663>.
>



-- 
Lars Toft Jacobsen
http://boxed.dk

**Comment by ltj** [comment]
OK, left the Object inheritance alone (any ideas?) but implemented your suggestion to let ```connect()``` accept a client object. Also added *connected* and *disconnected* events.

**Comment by gfwilliams** [comment]
Thanks! I was pretty sure that you could replace `Object.create(new MQTT(server, options))` with just `new MQTT(server, options)` - but I could well be wrong about that.

Looks fantastic anyway - I'll pull it in now :) I'll update the website with it when I release 1v72 - which I hope will be early next week.

**Comment by ltj** [comment]
Just checked. You are absolutely right about just using ```new```. I was put off by some error early on that stated ```on()``` and ```emit()```wasn't part of the prototype, so I just wrapped it in ```Object.create(p)``` to be on the safe side. I'll clean it up for the next pull request, since the semantics of the current instantiation is a bit unclear to me :)

**Pull request merged**
