### PR TITLE
Reconnect to MQTT on timeout

### PR DESCRIPTION
**Pull request by wanglingsong**
Added one more option "RECONNECT_INTERVAL" in constants C

### CODE REVIEW

**Comment by wanglingsong** [comment]
btw, the module minification of web IDE hardly work. So I have to manually add changed code into your minified source for testing. That was terrible!

**Comment by gfwilliams** [comment]
Thanks! I'm not sure what you mean by the minification not working - do you have any example? Could it be that you were using the online minifier and you had a bad internet connection?

**Comment by wanglingsong** [comment]
What minifier and minifier config used for the official min module? I didn't find it in the document.

**Comment by gfwilliams** [comment]
It's the closure compiler - you can find how it's done in `bin/minify.js`

**Comment by wanglingsong** [comment]
Thanks!

**Comment by jjok** [comment]
@gfwilliams This seems like a useful feature. Do you know why it was reverted in the next commit?

https://github.com/espruino/EspruinoDocs/commit/46f1054d843df9ed77aecbf1a5d8a77fec51ff64#diff-d136e58fdb064ae71881628760526607

Was that intentional, or did someone forget to rebase before that massive commit?

**Comment by gfwilliams** [comment]
It probably was someone who forgot to pull latest before their commit :( Some people start by massively refactoring everything to the way they like it, and while I try not to merge stuff like that if loads of people are reporting issues that were fixed in their changes then eventually I end up caving in and stuff like this happens.

Having said that I believe there are a few examples of auto-reconnect and it's only a few lines to do manually from the `disconnected` event.

It's important that we *don't* automatically default to connecting using `net` though as some people want to use `tls` to connect, and I recall there are even people using non-sockets (so MQTT over Serial, Bluetooth or other stuff)

**Comment by jjok** [comment]
OK, thanks. I saw the PR that added the feature and thought that I might be able to replace my own reconnect code with that, then was confused that it didn't exist anymore. No worries.

**Pull request merged**
