### PR TITLE
tried to update the 'connect' method, allowing to configure the brigh…

### PR DESCRIPTION
**Pull request by yerpj**
…tness of the display, through an option {brightness:value}, with value=[0..255]. Seems to work, but may not be linear

### CODE REVIEW

**Comment by gfwilliams** [comment]
closing this, as added a `setContrast` function

**Comment by yerpj** [comment]
Thank you so much @gfwilliams ! I'll use this right now!

**Comment by yerpj** [comment]
I just tested the new function ```setContrast()```. It seems that the command is misunderstood by the display. I wonder if we rather have to write this in two steps. I tried earlier with that one: 

```i2c.writeTo(addr, [0,0x81]);
i2c.writeTo(addr, [0,x]);
``` and it worked. 


Or maybe could we try ``` i2c.writeTo(addr, 0,0x81,0, c);```, I don't know...

**Comment by gfwilliams** [comment]
Ahh, Damn - i only tried the SPI one.  But the `{contrast: 0}` option works?

What about `i2c.writeTo(addr, 0,0x81,c);`? You could try that by hand, specifying I2C1/whatever and see if it works?

**Comment by yerpj** [comment]
```  g = require("SSD1306").connect(I2C2, function(){},{contrast:255}); ``` --> this works well

```  var value=3; //contrast value
I2C2.writeTo(0x3c,0,0x81,value);  ```  --> this works as well

**Comment by gfwilliams** [comment]
Great - I'll update it now

**Comment by yerpj** [comment]
@gfwilliams thanks a lot! Last question: Why are the files at http://www.espruino.com/modules not updated automatically based on the current git files? are they manually updated?

**Comment by gfwilliams** [comment]
Yes, it's manual. Sometimes modules get updated in there but they rely on a new version of the Espruino firmware - so then I hold off and release both together

**Comment by yerpj** [comment]
That make sense.  
Thank you for the update.

**Pull request closed without merging**
