### PR TITLE
Add Teletext-style / BBC Micro MODE 7 fonts

### PR DESCRIPTION
**Pull request by tomgidden**
These fonts are a little on the large side, so I've used heatshrink for storing the double-height versions.  They do not include the upper-bit graphics characters.

### CODE REVIEW

**Comment by gfwilliams** [comment]
That's awesome - thanks! Can't wait to see something using this :)

**Comment by tomgidden** [comment]
Thanks @gfwilliams... I have a watch face in development that uses it. It's a little too inefficient to push yet though.

Is there a delay in updating www.espruino.com/modules ? I assumed it was an automatic deployment.

All the best,
Tom

**Comment by gfwilliams** [comment]
No, I manually update it. Am doing it now but it's taking a while as I need to cope with heatshrink in fonts when the preview images are made ;)

**Comment by tomgidden** [comment]
Heh.. oops! Sorry about that :)

Incidentally, can you think of a simpler way than
```
const font = new Uint8Array(require('heatshrink').decompress(atob("…"))).reduce((p,c)=>p+String.fromCharCode(c),"");
```
for passing to `setFontCustom`?  I tried some other more straightforward ways than the `reduce` string construction, but didn't have much luck.

**Comment by gfwilliams** [comment]
Oh wow, didn't spot that. That's going to be crazy slow and possibly not great for memory usage.

`E.toString(require('heatshrink').decompress...)` is what you need :) I'll update them now

**Comment by gfwilliams** [comment]
They are actually now live (old versions) if you want to try...

**Comment by tomgidden** [comment]
Thanks...  I would, but my Bangle is stuck "Searching for GPS time". That's for another forum, though.

**Comment by gfwilliams** [comment]
> "Searching for GPS time"

https://www.espruino.com/Troubleshooting+Bangle.js#my-bangle-is-stuck-showing-searching-for-gps-time-

Likely by the time you get it sorted, the `toString` version will be live :)

**Pull request merged**
