### PR TITLE
AWS Tutorial & GCP Tutorial Fix

### PR DESCRIPTION
**Pull request by jaredfiacco2**
I added a tutorial on how to stream data into AWS IOT Core & use your Puck.js as a door alarm system! Been using it for a few days and it works really well!
Here's a demo! https://youtube.com/shorts/Ejb9RpYWCKc 

I also cleaned up the GCP tutorial from my last pull request. I switched the directory name halfway through making the tutorial and forgot to update it in the .md file. Also found a more fool-proof way to edit the nodered.service file.

I'm really glad I made these this weekend because I accidentally snapped my Raspberry Pi's SD card and had to do an entire system rebuild. These pictures & the document helped a ton!

### CODE REVIEW

**Comment by gfwilliams** [comment]
That's great - thank you! I'll put them live in a few minutes

**Comment by jaredfiacco2** [comment]
Hey Gordon, 
Thanks for putting them live!
I have a quick question, I see that the images, thumbnail, and video links aren't rendering in the live pages. 
Did I do something wrong? I used the format shown in the main readme file and the other tutorials as an example.

Is there another location where I have to add the new tutorial directory so those pngs can be added to the "refimages/" in the build? I looked at the other working tutorials to find examples but didn't see anything obvious. I'm sure I'm missing something though!

Thanks for the help in advance! :)

Format Used (pulled from the EspruinoDocs main readme):
[[http://youtu.be/VIDEOID]] puts a video on the page
Image Title Adds an image. Images should be in a directory named after the filename of the file referencing them (or the same directory as the file referencing them) 

Site Example: https://www.espruino.com/Puck.js+AWS+IOT
Ref Image Link: https://www.espruino.com/refimages/Puck.js_AWS_IOT_noedred-process.png

**Comment by gfwilliams** [comment]
Ahh, sorry - that one was my fault - I forgot to commit those extra images to the website.

The video doesn't show because it's a youtube shorts link (the first one we've had). I just changed it to `https://youtu.be/Ejb9RpYWCKc` and it seems to work fine. 

I also noticed it seems that the markdown parser we use doesn't like it what the three backticks for code come right after a line of text (it thinks they are part of the text) - so you need a blank line before and after.

I'll update the site (and this repo)  in a few minutes.

**Comment by jaredfiacco2** [comment]
Awesome! 
I just checked and both sites are working now. Thanks so much!!

**Pull request merged**
