### PR TITLE
Create fetch.md

### PR DESCRIPTION
**Pull request by JThobbyist**
goes with fetch.js

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks!

**Comment by gfwilliams** [comment]
Ahh - didn't spot this. There's a specific format for docs - see the other ones in the repo, and: http://www.espruino.com/Writing+Modules

I'll modify it now too

**Comment by JThobbyist** [comment]
Ah okay. I didn’t see that. I will use that format moving forward. Do you want me to fix the ones I uploaded and make a new PR?-Joe TeglasiOn Oct 12, 2022, at 3:42 AM, Gordon Williams ***@***.***> wrote:﻿
Ahh - didn't spot this. There's a specific format for docs - see the other ones in the repo, and: http://www.espruino.com/Writing+Modules
I'll modify it now too

**Comment by gfwilliams** [comment]
Thanks! But no, that's fine, I fixed it this morning.

If you wanted to remove the optional http provider it might be worth doing a PR for that though :)

**Pull request merged**
