### PR TITLE
Vvestm

### PR DESCRIPTION
**Pull request by VVESTM**
Hi,

Those 2 commits allow to get pressure and temperature from the sensors embedded in IKS01A1 ST expansion board.

Regards
Vincent

### CODE REVIEW

**Comment by gfwilliams** [comment]
Looks great - thanks!

Only things I can see:

* The blank line on line 2 of the `.md` files causes my parser grief. It's no big deal for me to change, but if you're adding extra stuff it'd be handy if it didn't have that.
* You're using globals for T0_OUT/etc. That's fine for one device - but if you have two devices plugged in then those are *the same globals* in each case, so calibration may get messed up? To fix it you could use `this.T0_OUT` instead.

**Comment by VVESTM** [comment]
OK Gordon, 

Thanks for this fast answer, I will push a new set of patches to take your remarks into account.

Vincent

**Comment by gfwilliams** [comment]
Great, thanks!

**Comment by VVESTM** [comment]
Thanks,

This will ease my demos and can be useful for other users getting the same hardware.
I guess it will be available through the web IDE in a few days ?

Regards
Vincent

**Comment by gfwilliams** [comment]
Yes, the update is manual. As it happens I was updating some other stuff as well, so it's live now!

**Comment by VVESTM** [comment]
effectively, I have checked and it is working !
good reactivity !! Have a good day !

**Pull request merged**
