### PR TITLE
Added Some Clarification on Build Scripts

### PR DESCRIPTION
**Pull request by chalkers**
Added commentary on the purpose of build.sh and build.js.

### CODE REVIEW

**Comment by chalkers** [comment]
@gfwilliams Didn't have chance to build out the javascript tasks yet. So updated docs with the current state of the build process.

**Comment by gfwilliams** [comment]
Thanks! Please could you just finish off `... at least once if you want the`? The sentence just ends there :)

**Comment by chalkers** [comment]
Opppps it was long night :)

**Comment by gfwilliams** [comment]
Thanks :)

**Pull request merged**
