### PR TITLE
Updating documentation

### PR DESCRIPTION
**Pull request by samehhady**
- update examples.
- update prefered nodejs ws server
- show all callbacks

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks - why did you remove me from the copyright. Obviously I didn't write the module (I didn't add copyright there) but generally if I end up writing documentation on a page I think it's fair I get mentioned too.

**Comment by samehhady** [comment]
oh i didn't meant to remove your copyright sorry about that. Shall i add it in the md or js file?

**Comment by samehhady** [comment]
aah sorry just found what i did :D i copied the first line from the old file i submitted. sorry again never meant to remove you for sure :D

**Comment by samehhady** [comment]
Updates and sorry again never meant it

**Comment by gfwilliams** [comment]
No worries, thanks! :)

**Pull request merged**
