### PR TITLE
Improvement: Update minify.js

### PR DESCRIPTION
**Pull request by MaBecker**
definittly improves minification - thanks to allObjects

### CODE REVIEW

**Comment by gfwilliams** [comment]
By improves, you mean it produces more compact code, or it fixes issues where bad code was created?

**Comment by MaBecker** [comment]
was impresssed by the more compact code.

**Comment by MaBecker** [comment]
was using this page for tests

https://closure-compiler.appspot.com/home

**Comment by MaBecker** [comment]
Just did some more research, there is to much risk to merge this as there are many min.js files that are generated by minify.js.
So better close it an try to find a way to pass additional compiler flag by command line or conf file.

**Comment by gfwilliams** [comment]
Well, this might still be ok - really it's just whether it tries to use any features Espruino doesn't support.

Sorry for the slow replies but I'm working through hundreds of emails after Christmas!

I believe it'd be pretty easy to add it to what's there already. Right now we already look to see if there's a comment inside the file that mentions only whitespace optimisation should be applied: https://github.com/espruino/EspruinoDocs/blob/master/bin/minify.js#L44

**Comment by MaBecker** [comment]
Ok, so let's open this again and add something.

**Pull request closed without merging**
