### PR TITLE
Module for Vizibles IoT platform 

### PR DESCRIPTION
**Pull request by pablorodiz**
Added the code and documentation for a new module for Espruino which helps on connecting things to the new [Vizibles](https://vizibles.com) IoT platform.

### CODE REVIEW

**Comment by gfwilliams** [comment]
Great, thanks! I'll tweak the URLs to the Spanish version a bit so that they work on the main espruino website (rather than just GitHub).

Where you do a bunch of `at.write(`'s you could just do `at.write(a+b+c+d)` - it'd minify down an awful lot better. Not sure if you want to change that?

Also, the Vizibles.js file looks pretty heavily based on the existing ESP8266 lib? It'd be nice to also give credit to the original authors in the header.

**Comment by pablorodiz** [comment]
Ok, I'll take your suggestions. Please wait for my next commits before merging.

**Comment by pablorodiz** [comment]
Done. And please feel free to tweak the URLs.

**Comment by gfwilliams** [comment]
Great - thanks!

**Pull request merged**
